version: '3.8'

services: 
  node_backend:
    container_name: node_docker
    image: node_docker:0.0.4
    build: 
      context: .
    ports:
      - "3000:3000"
    environment: 
      - EXTERNAL_PORT=3000
      - PGDATABASE=TestOrigin_db
      - PGUSER=djibril
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on: 
      - node_db
  node_db: 
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=djibril
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=TestOrigin_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}